-- Generated by protoc-gen-connect-lean from nopkg.proto. DO NOT EDIT.
module

public import Connect
public import EdgeGen.nopkg

public section

set_option linter.deprecated false

structure Greeter where
  greet : Connect.Context → Hello → Connect.RpcM Hello :=
    fun _ _ => throw (Connect.ConnectError.unimplemented "Greeter.Greet is not implemented")

namespace Greeter

/-- The fully-qualified service name. -/
def serviceName : String := "Greeter"

namespace Spec

/-- `Greeter.Greet`. -/
def greet : Connect.MethodSpec where
  service := "Greeter"
  name := "Greet"
  streamType := .unary
  idempotency := .unknown
  requestType := "Hello"
  responseType := "Hello"

end Spec

instance : Connect.ToService Greeter where
  toService impl := {
    name := "Greeter"
    methods := #[
      Connect.Method.unary Spec.greet impl.greet] }

/-- A client for `Greeter`. -/
structure Client where
  connection : Connect.Client

namespace Client

def greet (client : Client) (request : Hello) (options : Connect.CallOptions := {}) :
    Connect.RpcM Hello :=
  client.connection.unary Spec.greet request options

end Client

end Greeter

