module

public import Protobuf.ProtoMessage
public import Protobuf.Reflection
public import Protobuf.Json
public import Connect.Error

public section

/-!
# Codecs

Connect carries messages as binary protobuf (`proto`) or as ProtoJSON (`json`).
The content type names the codec, so every protocol negotiates it the same way.

A type can travel over Connect when it has a `Connect.Message` instance. Every
message generated by `protoc-gen-lean4` gets one for free, from its
`ProtoMessage` (binary) and `ReflectMessage` (JSON) instances.
-/

namespace Connect

/-- How messages are serialized. -/
inductive Codec where
  /-- Binary protobuf. -/
  | proto
  /-- ProtoJSON, the canonical JSON mapping of protobuf. -/
  | json
  deriving DecidableEq, Repr, Inhabited, Hashable

namespace Codec

/-- The name used in content types: `application/proto`, `application/grpc+json`. -/
@[expose] def name : Codec → String
  | proto => "proto"
  | json => "json"

@[expose] def ofName? : String → Option Codec
  | "proto" => some proto
  | "json" => some json
  | _ => none

theorem ofName?_name (c : Codec) : ofName? c.name = some c := by
  cases c <;> rfl

instance : ToString Codec := ⟨name⟩

end Codec

/-- A message type Connect can send and receive. -/
class Message (α : Type) where
  /-- The fully-qualified protobuf name, such as `connectrpc.eliza.v1.SayRequest`. -/
  typeName : String
  encodeBinary : α → Except String ByteArray
  decodeBinary : ByteArray → Except String α
  encodeJson : α → IO (Except String ByteArray)
  decodeJson : ByteArray → IO (Except String α)

/-- A readable description of a binary protobuf failure. -/
def protoErrorString : Protobuf.Encoding.ProtoError → String
  | .truncated => "truncated message"
  | .invalidVarint => "invalid varint"
  | .invalidWireType e => s!"invalid wire type: {e}"
  | .invalidBuffer e => s!"invalid buffer: {e}"
  | .missingRequiredField e => s!"missing required field: {e}"
  | .userError e => e

/-- Messages generated by `protoc-gen-lean4` are Connect messages. JSON parsing
    ignores unknown fields, as every Connect implementation does, and resolves
    `google.protobuf.Any` through the generated descriptor pool. -/
instance [Protobuf.ProtoMessage α] [Protobuf.Reflection.ReflectMessage α] : Message α where
  typeName := (Protobuf.Reflection.messageDescriptor α).fullName
  encodeBinary a := (Protobuf.encode a).mapError protoErrorString
  decodeBinary b := (Protobuf.decodeThe α b).mapError protoErrorString
  encodeJson a := do
    let r ← Protobuf.Json.toJsonString a Protobuf.Json.PrintOptions.withGeneratedPool
    return r.map (·.toUTF8) |>.mapError toString
  decodeJson b := do
    let some text := String.fromUTF8? b
      | return .error "JSON is not valid UTF-8"
    let opts := Protobuf.Json.ParseOptions.withGeneratedPool { discardUnknownFields := true }
    let r ← Protobuf.Json.fromJsonString text α opts
    return r.mapError toString

namespace Codec

/-- Serializes a message. A failure is an `internal` error: the message itself
    is at fault, not the peer. -/
def encode [Message α] (c : Codec) (msg : α) : IO (Except ConnectError ByteArray) := do
  let r ← match c with
    | proto => pure (Message.encodeBinary msg)
    | json => Message.encodeJson msg
  return r.mapError fun e =>
    .internal s!"failed to marshal {Message.typeName α} as {c.name}: {e}"

/-- Parses a message. A failure is an `invalid_argument` error, since the peer
    sent something malformed. -/
def decode [Message α] (c : Codec) (bytes : ByteArray) : IO (Except ConnectError α) := do
  let r ← match c with
    | proto => pure (Message.decodeBinary bytes)
    | json => Message.decodeJson bytes
  return r.mapError fun e =>
    .invalidArgument s!"failed to unmarshal {Message.typeName α} from {c.name}: {e}"

end Codec

end Connect
