-- Generated by protoc-gen-connect-lean from edge/v1/edge.proto. DO NOT EDIT.
module

public import Connect
public import EdgeGen.edge.v1.edge
public import EdgeGen.edge.v1.types

public section

set_option linter.deprecated false

namespace edge.v1

/--
Method names that collide with what the generator adds, or with Lean keywords.
-/
structure EdgeService where
  /--
  A method called Client: the client structure is `Client` too.
  -/
  client : Connect.Context → edge.v1.Ping → Connect.RpcM edge.v1.Pong :=
    fun _ _ => throw (Connect.ConnectError.unimplemented "edge.v1.EdgeService.Client is not implemented")
  serviceName_ : Connect.Context → edge.v1.Ping → Connect.RpcM edge.v1.Pong :=
    fun _ _ => throw (Connect.ConnectError.unimplemented "edge.v1.EdgeService.ServiceName is not implemented")
  mk_ : Connect.Context → edge.v1.Ping → Connect.RpcM edge.v1.Pong :=
    fun _ _ => throw (Connect.ConnectError.unimplemented "edge.v1.EdgeService.Mk is not implemented")
  connection_ : Connect.Context → edge.v1.Ping → Connect.RpcM edge.v1.Pong :=
    fun _ _ => throw (Connect.ConnectError.unimplemented "edge.v1.EdgeService.Connection is not implemented")
  «end» : Connect.Context → edge.v1.Ping → Connect.RpcM edge.v1.Pong :=
    fun _ _ => throw (Connect.ConnectError.unimplemented "edge.v1.EdgeService.End is not implemented")
  «where» : Connect.Context → Connect.RequestStream edge.v1.Ping → Connect.ResponseStream edge.v1.Pong → Connect.RpcM Unit :=
    fun _ _ _ => throw (Connect.ConnectError.unimplemented "edge.v1.EdgeService.Where is not implemented")
  get_thing : Connect.Context → edge.v1.Ping → Connect.RpcM edge.v1.Pong :=
    fun _ _ => throw (Connect.ConnectError.unimplemented "edge.v1.EdgeService.get_thing is not implemented")
  deprecated : Connect.Context → edge.v1.Ping → Connect.RpcM edge.v1.Pong :=
    fun _ _ => throw (Connect.ConnectError.unimplemented "edge.v1.EdgeService.Deprecated is not implemented")

namespace EdgeService

/-- The fully-qualified service name. -/
def serviceName : String := "edge.v1.EdgeService"

namespace Spec

/-- `edge.v1.EdgeService.Client`. -/
def client : Connect.MethodSpec where
  service := "edge.v1.EdgeService"
  name := "Client"
  streamType := .unary
  idempotency := .unknown
  requestType := "edge.v1.Ping"
  responseType := "edge.v1.Pong"

/-- `edge.v1.EdgeService.ServiceName`. -/
def serviceName_ : Connect.MethodSpec where
  service := "edge.v1.EdgeService"
  name := "ServiceName"
  streamType := .unary
  idempotency := .unknown
  requestType := "edge.v1.Ping"
  responseType := "edge.v1.Pong"

/-- `edge.v1.EdgeService.Mk`. -/
def mk_ : Connect.MethodSpec where
  service := "edge.v1.EdgeService"
  name := "Mk"
  streamType := .unary
  idempotency := .unknown
  requestType := "edge.v1.Ping"
  responseType := "edge.v1.Pong"

/-- `edge.v1.EdgeService.Connection`. -/
def connection_ : Connect.MethodSpec where
  service := "edge.v1.EdgeService"
  name := "Connection"
  streamType := .unary
  idempotency := .unknown
  requestType := "edge.v1.Ping"
  responseType := "edge.v1.Pong"

/-- `edge.v1.EdgeService.End`. -/
def «end» : Connect.MethodSpec where
  service := "edge.v1.EdgeService"
  name := "End"
  streamType := .unary
  idempotency := .unknown
  requestType := "edge.v1.Ping"
  responseType := "edge.v1.Pong"

/-- `edge.v1.EdgeService.Where`. -/
def «where» : Connect.MethodSpec where
  service := "edge.v1.EdgeService"
  name := "Where"
  streamType := .bidiStream
  idempotency := .unknown
  requestType := "edge.v1.Ping"
  responseType := "edge.v1.Pong"

/-- `edge.v1.EdgeService.get_thing`. -/
def get_thing : Connect.MethodSpec where
  service := "edge.v1.EdgeService"
  name := "get_thing"
  streamType := .unary
  idempotency := .noSideEffects
  requestType := "edge.v1.Ping"
  responseType := "edge.v1.Pong"

/-- `edge.v1.EdgeService.Deprecated`. -/
def deprecated : Connect.MethodSpec where
  service := "edge.v1.EdgeService"
  name := "Deprecated"
  streamType := .unary
  idempotency := .unknown
  requestType := "edge.v1.Ping"
  responseType := "edge.v1.Pong"

end Spec

instance : Connect.ToService EdgeService where
  toService impl := {
    name := "edge.v1.EdgeService"
    methods := #[
      Connect.Method.unary Spec.client impl.client,
      Connect.Method.unary Spec.serviceName_ impl.serviceName_,
      Connect.Method.unary Spec.mk_ impl.mk_,
      Connect.Method.unary Spec.connection_ impl.connection_,
      Connect.Method.unary Spec.«end» impl.«end»,
      Connect.Method.bidiStream Spec.«where» impl.«where»,
      Connect.Method.unary Spec.get_thing impl.get_thing,
      Connect.Method.unary Spec.deprecated impl.deprecated] }

/-- A client for `edge.v1.EdgeService`. -/
structure Client where
  connection : Connect.Client

namespace Client

/--
A method called Client: the client structure is `Client` too.
-/
def client (client : Client) (request : edge.v1.Ping) (options : Connect.CallOptions := {}) :
    Connect.RpcM edge.v1.Pong :=
  client.connection.unary Spec.client request options

def serviceName_ (client : Client) (request : edge.v1.Ping) (options : Connect.CallOptions := {}) :
    Connect.RpcM edge.v1.Pong :=
  client.connection.unary Spec.serviceName_ request options

def mk_ (client : Client) (request : edge.v1.Ping) (options : Connect.CallOptions := {}) :
    Connect.RpcM edge.v1.Pong :=
  client.connection.unary Spec.mk_ request options

def connection_ (client : Client) (request : edge.v1.Ping) (options : Connect.CallOptions := {}) :
    Connect.RpcM edge.v1.Pong :=
  client.connection.unary Spec.connection_ request options

def «end» (client : Client) (request : edge.v1.Ping) (options : Connect.CallOptions := {}) :
    Connect.RpcM edge.v1.Pong :=
  client.connection.unary Spec.«end» request options

def «where» (client : Client) (options : Connect.CallOptions := {}) :
    Connect.RpcM (Connect.BidiStreamCall edge.v1.Ping edge.v1.Pong) :=
  client.connection.bidiStream Spec.«where» options

def get_thing (client : Client) (request : edge.v1.Ping) (options : Connect.CallOptions := {}) :
    Connect.RpcM edge.v1.Pong :=
  client.connection.unary Spec.get_thing request options

@[deprecated "edge.v1.EdgeService.Deprecated is deprecated in its .proto file" (since := "")]
def deprecated (client : Client) (request : edge.v1.Ping) (options : Connect.CallOptions := {}) :
    Connect.RpcM edge.v1.Pong :=
  client.connection.unary Spec.deprecated request options

end Client

end EdgeService

/--
A service with no methods at all.
-/
structure EmptyService where
  /-- The service declares no methods. -/
  «unit» : Unit := ()

namespace EmptyService

/-- The fully-qualified service name. -/
def serviceName : String := "edge.v1.EmptyService"

namespace Spec

end Spec

instance : Connect.ToService EmptyService where
  toService _ := {
    name := "edge.v1.EmptyService"
    methods := #[] }

/-- A client for `edge.v1.EmptyService`. -/
structure Client where
  connection : Connect.Client

namespace Client

end Client

end EmptyService

/--
A service on its way out.
-/
@[deprecated "edge.v1.OldService is deprecated in its .proto file" (since := "")]
structure OldService where
  ping : Connect.Context → edge.v1.Ping → Connect.RpcM edge.v1.Pong :=
    fun _ _ => throw (Connect.ConnectError.unimplemented "edge.v1.OldService.Ping is not implemented")

namespace OldService

/-- The fully-qualified service name. -/
def serviceName : String := "edge.v1.OldService"

namespace Spec

/-- `edge.v1.OldService.Ping`. -/
def ping : Connect.MethodSpec where
  service := "edge.v1.OldService"
  name := "Ping"
  streamType := .unary
  idempotency := .unknown
  requestType := "edge.v1.Ping"
  responseType := "edge.v1.Pong"

end Spec

instance : Connect.ToService OldService where
  toService impl := {
    name := "edge.v1.OldService"
    methods := #[
      Connect.Method.unary Spec.ping impl.ping] }

/-- A client for `edge.v1.OldService`. -/
@[deprecated "edge.v1.OldService is deprecated in its .proto file" (since := "")]
structure Client where
  connection : Connect.Client

namespace Client

def ping (client : Client) (request : edge.v1.Ping) (options : Connect.CallOptions := {}) :
    Connect.RpcM edge.v1.Pong :=
  client.connection.unary Spec.ping request options

end Client

end OldService

end edge.v1
