-- Generated by protoc-gen-connect-lean from edge/v1/kinds.proto. DO NOT EDIT.
module

public import Connect
public import EdgeGen.edge.v1.kinds
public import EdgeGen.edge.v1.types

public section

set_option linter.deprecated false

namespace edge.v1

/--
One method of each kind, for the interceptor tests.
-/
structure KindsService where
  unary : Connect.Context → edge.v1.Ping → Connect.RpcM edge.v1.Pong :=
    fun _ _ => throw (Connect.ConnectError.unimplemented "edge.v1.KindsService.Unary is not implemented")
  clientStream : Connect.Context → Connect.RequestStream edge.v1.Ping → Connect.RpcM edge.v1.Pong :=
    fun _ _ => throw (Connect.ConnectError.unimplemented "edge.v1.KindsService.ClientStream is not implemented")
  serverStream : Connect.Context → edge.v1.Ping → Connect.ResponseStream edge.v1.Pong → Connect.RpcM Unit :=
    fun _ _ _ => throw (Connect.ConnectError.unimplemented "edge.v1.KindsService.ServerStream is not implemented")
  bidiStream : Connect.Context → Connect.RequestStream edge.v1.Ping → Connect.ResponseStream edge.v1.Pong → Connect.RpcM Unit :=
    fun _ _ _ => throw (Connect.ConnectError.unimplemented "edge.v1.KindsService.BidiStream is not implemented")

namespace KindsService

/-- The fully-qualified service name. -/
def serviceName : String := "edge.v1.KindsService"

namespace Spec

/-- `edge.v1.KindsService.Unary`. -/
def unary : Connect.MethodSpec where
  service := "edge.v1.KindsService"
  name := "Unary"
  streamType := .unary
  idempotency := .unknown
  requestType := "edge.v1.Ping"
  responseType := "edge.v1.Pong"

/-- `edge.v1.KindsService.ClientStream`. -/
def clientStream : Connect.MethodSpec where
  service := "edge.v1.KindsService"
  name := "ClientStream"
  streamType := .clientStream
  idempotency := .unknown
  requestType := "edge.v1.Ping"
  responseType := "edge.v1.Pong"

/-- `edge.v1.KindsService.ServerStream`. -/
def serverStream : Connect.MethodSpec where
  service := "edge.v1.KindsService"
  name := "ServerStream"
  streamType := .serverStream
  idempotency := .unknown
  requestType := "edge.v1.Ping"
  responseType := "edge.v1.Pong"

/-- `edge.v1.KindsService.BidiStream`. -/
def bidiStream : Connect.MethodSpec where
  service := "edge.v1.KindsService"
  name := "BidiStream"
  streamType := .bidiStream
  idempotency := .unknown
  requestType := "edge.v1.Ping"
  responseType := "edge.v1.Pong"

end Spec

instance : Connect.ToService KindsService where
  toService impl := {
    name := "edge.v1.KindsService"
    methods := #[
      Connect.Method.unary Spec.unary impl.unary,
      Connect.Method.clientStream Spec.clientStream impl.clientStream,
      Connect.Method.serverStream Spec.serverStream impl.serverStream,
      Connect.Method.bidiStream Spec.bidiStream impl.bidiStream] }

/-- A client for `edge.v1.KindsService`. -/
structure Client where
  connection : Connect.Client

namespace Client

def unary (client : Client) (request : edge.v1.Ping) (options : Connect.CallOptions := {}) :
    Connect.RpcM edge.v1.Pong :=
  client.connection.unary Spec.unary request options

def clientStream (client : Client) (options : Connect.CallOptions := {}) :
    Connect.RpcM (Connect.ClientStreamCall edge.v1.Ping edge.v1.Pong) :=
  client.connection.clientStream Spec.clientStream options

def serverStream (client : Client) (request : edge.v1.Ping) (options : Connect.CallOptions := {}) :
    Connect.RpcM (Connect.ServerStreamCall edge.v1.Pong) :=
  client.connection.serverStream Spec.serverStream request options

def bidiStream (client : Client) (options : Connect.CallOptions := {}) :
    Connect.RpcM (Connect.BidiStreamCall edge.v1.Ping edge.v1.Pong) :=
  client.connection.bidiStream Spec.bidiStream options

end Client

end KindsService

end edge.v1
