-- Generated by protoc-gen-connect-lean from connectrpc/eliza/v1/eliza.proto. DO NOT EDIT.
module

public import Connect
public import ElizaGen.connectrpc.eliza.v1.eliza

public section

set_option linter.deprecated false

namespace connectrpc.eliza.v1

/--
ElizaService provides a way to talk to Eliza, a port of the DOCTOR script
for Joseph Weizenbaum's original ELIZA program. Created in the mid-1960s at
the MIT Artificial Intelligence Laboratory, ELIZA demonstrates the
superficiality of human-computer communication. DOCTOR simulates a
psychotherapist, and is commonly found as an Easter egg in emacs
distributions.
-/
structure ElizaService where
  /--
  Say is a unary RPC. Eliza responds to the prompt with a single sentence.
  -/
  say : Connect.Context → connectrpc.eliza.v1.SayRequest → Connect.RpcM connectrpc.eliza.v1.SayResponse :=
    fun _ _ => throw (Connect.ConnectError.unimplemented "connectrpc.eliza.v1.ElizaService.Say is not implemented")
  /--
  Converse is a bidirectional RPC. The caller may exchange multiple
  back-and-forth messages with Eliza over a long-lived connection. Eliza
  responds to each ConverseRequest with a ConverseResponse.
  -/
  converse : Connect.Context → Connect.RequestStream connectrpc.eliza.v1.ConverseRequest → Connect.ResponseStream connectrpc.eliza.v1.ConverseResponse → Connect.RpcM Unit :=
    fun _ _ _ => throw (Connect.ConnectError.unimplemented "connectrpc.eliza.v1.ElizaService.Converse is not implemented")
  /--
  Introduce is a server streaming RPC. Given the caller's name, Eliza
  returns a stream of sentences to introduce itself.
  -/
  introduce : Connect.Context → connectrpc.eliza.v1.IntroduceRequest → Connect.ResponseStream connectrpc.eliza.v1.IntroduceResponse → Connect.RpcM Unit :=
    fun _ _ _ => throw (Connect.ConnectError.unimplemented "connectrpc.eliza.v1.ElizaService.Introduce is not implemented")

namespace ElizaService

/-- The fully-qualified service name. -/
def serviceName : String := "connectrpc.eliza.v1.ElizaService"

namespace Spec

/-- `connectrpc.eliza.v1.ElizaService.Say`. -/
def say : Connect.MethodSpec where
  service := "connectrpc.eliza.v1.ElizaService"
  name := "Say"
  streamType := .unary
  idempotency := .noSideEffects
  requestType := "connectrpc.eliza.v1.SayRequest"
  responseType := "connectrpc.eliza.v1.SayResponse"

/-- `connectrpc.eliza.v1.ElizaService.Converse`. -/
def converse : Connect.MethodSpec where
  service := "connectrpc.eliza.v1.ElizaService"
  name := "Converse"
  streamType := .bidiStream
  idempotency := .unknown
  requestType := "connectrpc.eliza.v1.ConverseRequest"
  responseType := "connectrpc.eliza.v1.ConverseResponse"

/-- `connectrpc.eliza.v1.ElizaService.Introduce`. -/
def introduce : Connect.MethodSpec where
  service := "connectrpc.eliza.v1.ElizaService"
  name := "Introduce"
  streamType := .serverStream
  idempotency := .unknown
  requestType := "connectrpc.eliza.v1.IntroduceRequest"
  responseType := "connectrpc.eliza.v1.IntroduceResponse"

end Spec

instance : Connect.ToService ElizaService where
  toService impl := {
    name := "connectrpc.eliza.v1.ElizaService"
    methods := #[
      Connect.Method.unary Spec.say impl.say,
      Connect.Method.bidiStream Spec.converse impl.converse,
      Connect.Method.serverStream Spec.introduce impl.introduce] }

/-- A client for `connectrpc.eliza.v1.ElizaService`. -/
structure Client where
  connection : Connect.Client

namespace Client

/--
Say is a unary RPC. Eliza responds to the prompt with a single sentence.
-/
def say (client : Client) (request : connectrpc.eliza.v1.SayRequest) (options : Connect.CallOptions := {}) :
    Connect.RpcM connectrpc.eliza.v1.SayResponse :=
  client.connection.unary Spec.say request options

/--
Converse is a bidirectional RPC. The caller may exchange multiple
back-and-forth messages with Eliza over a long-lived connection. Eliza
responds to each ConverseRequest with a ConverseResponse.
-/
def converse (client : Client) (options : Connect.CallOptions := {}) :
    Connect.RpcM (Connect.BidiStreamCall connectrpc.eliza.v1.ConverseRequest connectrpc.eliza.v1.ConverseResponse) :=
  client.connection.bidiStream Spec.converse options

/--
Introduce is a server streaming RPC. Given the caller's name, Eliza
returns a stream of sentences to introduce itself.
-/
def introduce (client : Client) (request : connectrpc.eliza.v1.IntroduceRequest) (options : Connect.CallOptions := {}) :
    Connect.RpcM (Connect.ServerStreamCall connectrpc.eliza.v1.IntroduceResponse) :=
  client.connection.serverStream Spec.introduce request options

end Client

end ElizaService

end connectrpc.eliza.v1
