-- Generated by protoc-gen-connect-lean from connectrpc/conformance/v1/service.proto. DO NOT EDIT.
module

public import Connect
public import ConformanceGen.connectrpc.conformance.v1.service

public section

set_option linter.deprecated false

namespace connectrpc.conformance.v1

/--
The service implemented by conformance test servers. This is implemented by
the reference servers, used to test clients, and is expected to be implemented
by test servers, since this is the service used by reference clients.

Test servers must implement the service as described.
-/
structure ConformanceService where
  /--
  A unary operation. The request indicates the response headers and trailers
  and also indicates either a response message or an error to send back.

  Response message data is specified as bytes. The service should echo back
  request properties in the ConformancePayload and then include the message
  data in the data field.

  If the response_delay_ms duration is specified, the server should wait the
  given duration after reading the request before sending the corresponding
  response.

  Servers should allow the response definition to be unset in the request and
  if it is, set no response headers or trailers and return no response data.
  The returned payload should only contain the request info.
  -/
  unary : Connect.Context → connectrpc.conformance.v1.UnaryRequest → Connect.RpcM connectrpc.conformance.v1.UnaryResponse :=
    fun _ _ => throw (Connect.ConnectError.unimplemented "connectrpc.conformance.v1.ConformanceService.Unary is not implemented")
  /--
  A server-streaming operation. The request indicates the response headers,
  response messages, trailers, and an optional error to send back. The
  response data should be sent in the order indicated, and the server should
  wait between sending response messages as indicated.

  Response message data is specified as bytes. The service should echo back
  request properties in the first ConformancePayload, and then include the
  message data in the data field. Subsequent messages after the first one
  should contain only the data field.

  Servers should immediately send response headers on the stream before sleeping
  for any specified response delay and/or sending the first message so that
  clients can be unblocked reading response headers.

  If a response definition is not specified OR is specified, but response data
  is empty, the server should skip sending anything on the stream. When there
  are no responses to send, servers should throw an error if one is provided
  and return without error if one is not. Stream headers and trailers should
  still be set on the stream if provided regardless of whether a response is
  sent or an error is thrown.
  -/
  serverStream : Connect.Context → connectrpc.conformance.v1.ServerStreamRequest → Connect.ResponseStream connectrpc.conformance.v1.ServerStreamResponse → Connect.RpcM Unit :=
    fun _ _ _ => throw (Connect.ConnectError.unimplemented "connectrpc.conformance.v1.ConformanceService.ServerStream is not implemented")
  /--
  A client-streaming operation. The first request indicates the response
  headers and trailers and also indicates either a response message or an
  error to send back.

  Response message data is specified as bytes. The service should echo back
  request properties, including all request messages in the order they were
  received, in the ConformancePayload and then include the message data in
  the data field.

  If the input stream is empty, the server's response will include no data,
  only the request properties (headers, timeout).

  Servers should only read the response definition from the first message in
  the stream and should ignore any definition set in subsequent messages.

  Servers should allow the response definition to be unset in the request and
  if it is, set no response headers or trailers and return no response data.
  The returned payload should only contain the request info.
  -/
  clientStream : Connect.Context → Connect.RequestStream connectrpc.conformance.v1.ClientStreamRequest → Connect.RpcM connectrpc.conformance.v1.ClientStreamResponse :=
    fun _ _ => throw (Connect.ConnectError.unimplemented "connectrpc.conformance.v1.ConformanceService.ClientStream is not implemented")
  /--
  A bidirectional-streaming operation. The first request indicates the response
  headers, response messages, trailers, and an optional error to send back.
  The response data should be sent in the order indicated, and the server
  should wait between sending response messages as indicated.

  Response message data is specified as bytes and should be included in the
  data field of the ConformancePayload in each response.

  Servers should send responses indicated according to the rules of half duplex
  vs. full duplex streams. Once all responses are sent, the server should either
  return an error if specified or close the stream without error.

  Servers should immediately send response headers on the stream before sleeping
  for any specified response delay and/or sending the first message so that
  clients can be unblocked reading response headers.

  If a response definition is not specified OR is specified, but response data
  is empty, the server should skip sending anything on the stream. Stream
  headers and trailers should always be set on the stream if provided
  regardless of whether a response is sent or an error is thrown.

  If the full_duplex field is true:
  - the handler should read one request and then send back one response, and
    then alternate, reading another request and then sending back another response, etc.

  - if the server receives a request and has no responses to send, it
    should throw the error specified in the request.

  - the service should echo back all request properties in the first response
    including the last received request. Subsequent responses should only
    echo back the last received request.

  - if the response_delay_ms duration is specified, the server should wait the given
    duration after reading the request before sending the corresponding
    response.

  If the full_duplex field is false:
  - the handler should read all requests until the client is done sending.
    Once all requests are read, the server should then send back any responses
    specified in the response definition.

  - the server should echo back all request properties, including all request
    messages in the order they were received, in the first response. Subsequent
    responses should only include the message data in the data field.

  - if the response_delay_ms duration is specified, the server should wait that
    long in between sending each response message.
  -/
  bidiStream : Connect.Context → Connect.RequestStream connectrpc.conformance.v1.BidiStreamRequest → Connect.ResponseStream connectrpc.conformance.v1.BidiStreamResponse → Connect.RpcM Unit :=
    fun _ _ _ => throw (Connect.ConnectError.unimplemented "connectrpc.conformance.v1.ConformanceService.BidiStream is not implemented")
  /--
  A unary endpoint that the server should not implement and should instead
  return an unimplemented error when invoked.
  -/
  unimplemented : Connect.Context → connectrpc.conformance.v1.UnimplementedRequest → Connect.RpcM connectrpc.conformance.v1.UnimplementedResponse :=
    fun _ _ => throw (Connect.ConnectError.unimplemented "connectrpc.conformance.v1.ConformanceService.Unimplemented is not implemented")
  /--
  A unary endpoint denoted as having no side effects (i.e. idempotent).
  Implementations should use an HTTP GET when invoking this endpoint and
  leverage query parameters to send data.
  -/
  idempotentUnary : Connect.Context → connectrpc.conformance.v1.IdempotentUnaryRequest → Connect.RpcM connectrpc.conformance.v1.IdempotentUnaryResponse :=
    fun _ _ => throw (Connect.ConnectError.unimplemented "connectrpc.conformance.v1.ConformanceService.IdempotentUnary is not implemented")

namespace ConformanceService

/-- The fully-qualified service name. -/
def serviceName : String := "connectrpc.conformance.v1.ConformanceService"

namespace Spec

/-- `connectrpc.conformance.v1.ConformanceService.Unary`. -/
def unary : Connect.MethodSpec where
  service := "connectrpc.conformance.v1.ConformanceService"
  name := "Unary"
  streamType := .unary
  idempotency := .unknown
  requestType := "connectrpc.conformance.v1.UnaryRequest"
  responseType := "connectrpc.conformance.v1.UnaryResponse"

/-- `connectrpc.conformance.v1.ConformanceService.ServerStream`. -/
def serverStream : Connect.MethodSpec where
  service := "connectrpc.conformance.v1.ConformanceService"
  name := "ServerStream"
  streamType := .serverStream
  idempotency := .unknown
  requestType := "connectrpc.conformance.v1.ServerStreamRequest"
  responseType := "connectrpc.conformance.v1.ServerStreamResponse"

/-- `connectrpc.conformance.v1.ConformanceService.ClientStream`. -/
def clientStream : Connect.MethodSpec where
  service := "connectrpc.conformance.v1.ConformanceService"
  name := "ClientStream"
  streamType := .clientStream
  idempotency := .unknown
  requestType := "connectrpc.conformance.v1.ClientStreamRequest"
  responseType := "connectrpc.conformance.v1.ClientStreamResponse"

/-- `connectrpc.conformance.v1.ConformanceService.BidiStream`. -/
def bidiStream : Connect.MethodSpec where
  service := "connectrpc.conformance.v1.ConformanceService"
  name := "BidiStream"
  streamType := .bidiStream
  idempotency := .unknown
  requestType := "connectrpc.conformance.v1.BidiStreamRequest"
  responseType := "connectrpc.conformance.v1.BidiStreamResponse"

/-- `connectrpc.conformance.v1.ConformanceService.Unimplemented`. -/
def unimplemented : Connect.MethodSpec where
  service := "connectrpc.conformance.v1.ConformanceService"
  name := "Unimplemented"
  streamType := .unary
  idempotency := .unknown
  requestType := "connectrpc.conformance.v1.UnimplementedRequest"
  responseType := "connectrpc.conformance.v1.UnimplementedResponse"

/-- `connectrpc.conformance.v1.ConformanceService.IdempotentUnary`. -/
def idempotentUnary : Connect.MethodSpec where
  service := "connectrpc.conformance.v1.ConformanceService"
  name := "IdempotentUnary"
  streamType := .unary
  idempotency := .noSideEffects
  requestType := "connectrpc.conformance.v1.IdempotentUnaryRequest"
  responseType := "connectrpc.conformance.v1.IdempotentUnaryResponse"

end Spec

instance : Connect.ToService ConformanceService where
  toService impl := {
    name := "connectrpc.conformance.v1.ConformanceService"
    methods := #[
      Connect.Method.unary Spec.unary impl.unary,
      Connect.Method.serverStream Spec.serverStream impl.serverStream,
      Connect.Method.clientStream Spec.clientStream impl.clientStream,
      Connect.Method.bidiStream Spec.bidiStream impl.bidiStream,
      Connect.Method.unary Spec.unimplemented impl.unimplemented,
      Connect.Method.unary Spec.idempotentUnary impl.idempotentUnary] }

/-- A client for `connectrpc.conformance.v1.ConformanceService`. -/
structure Client where
  connection : Connect.Client

namespace Client

/--
A unary operation. The request indicates the response headers and trailers
and also indicates either a response message or an error to send back.

Response message data is specified as bytes. The service should echo back
request properties in the ConformancePayload and then include the message
data in the data field.

If the response_delay_ms duration is specified, the server should wait the
given duration after reading the request before sending the corresponding
response.

Servers should allow the response definition to be unset in the request and
if it is, set no response headers or trailers and return no response data.
The returned payload should only contain the request info.
-/
def unary (client : Client) (request : connectrpc.conformance.v1.UnaryRequest) (options : Connect.CallOptions := {}) :
    Connect.RpcM connectrpc.conformance.v1.UnaryResponse :=
  client.connection.unary Spec.unary request options

/--
A server-streaming operation. The request indicates the response headers,
response messages, trailers, and an optional error to send back. The
response data should be sent in the order indicated, and the server should
wait between sending response messages as indicated.

Response message data is specified as bytes. The service should echo back
request properties in the first ConformancePayload, and then include the
message data in the data field. Subsequent messages after the first one
should contain only the data field.

Servers should immediately send response headers on the stream before sleeping
for any specified response delay and/or sending the first message so that
clients can be unblocked reading response headers.

If a response definition is not specified OR is specified, but response data
is empty, the server should skip sending anything on the stream. When there
are no responses to send, servers should throw an error if one is provided
and return without error if one is not. Stream headers and trailers should
still be set on the stream if provided regardless of whether a response is
sent or an error is thrown.
-/
def serverStream (client : Client) (request : connectrpc.conformance.v1.ServerStreamRequest) (options : Connect.CallOptions := {}) :
    Connect.RpcM (Connect.ServerStreamCall connectrpc.conformance.v1.ServerStreamResponse) :=
  client.connection.serverStream Spec.serverStream request options

/--
A client-streaming operation. The first request indicates the response
headers and trailers and also indicates either a response message or an
error to send back.

Response message data is specified as bytes. The service should echo back
request properties, including all request messages in the order they were
received, in the ConformancePayload and then include the message data in
the data field.

If the input stream is empty, the server's response will include no data,
only the request properties (headers, timeout).

Servers should only read the response definition from the first message in
the stream and should ignore any definition set in subsequent messages.

Servers should allow the response definition to be unset in the request and
if it is, set no response headers or trailers and return no response data.
The returned payload should only contain the request info.
-/
def clientStream (client : Client) (options : Connect.CallOptions := {}) :
    Connect.RpcM (Connect.ClientStreamCall connectrpc.conformance.v1.ClientStreamRequest connectrpc.conformance.v1.ClientStreamResponse) :=
  client.connection.clientStream Spec.clientStream options

/--
A bidirectional-streaming operation. The first request indicates the response
headers, response messages, trailers, and an optional error to send back.
The response data should be sent in the order indicated, and the server
should wait between sending response messages as indicated.

Response message data is specified as bytes and should be included in the
data field of the ConformancePayload in each response.

Servers should send responses indicated according to the rules of half duplex
vs. full duplex streams. Once all responses are sent, the server should either
return an error if specified or close the stream without error.

Servers should immediately send response headers on the stream before sleeping
for any specified response delay and/or sending the first message so that
clients can be unblocked reading response headers.

If a response definition is not specified OR is specified, but response data
is empty, the server should skip sending anything on the stream. Stream
headers and trailers should always be set on the stream if provided
regardless of whether a response is sent or an error is thrown.

If the full_duplex field is true:
- the handler should read one request and then send back one response, and
  then alternate, reading another request and then sending back another response, etc.

- if the server receives a request and has no responses to send, it
  should throw the error specified in the request.

- the service should echo back all request properties in the first response
  including the last received request. Subsequent responses should only
  echo back the last received request.

- if the response_delay_ms duration is specified, the server should wait the given
  duration after reading the request before sending the corresponding
  response.

If the full_duplex field is false:
- the handler should read all requests until the client is done sending.
  Once all requests are read, the server should then send back any responses
  specified in the response definition.

- the server should echo back all request properties, including all request
  messages in the order they were received, in the first response. Subsequent
  responses should only include the message data in the data field.

- if the response_delay_ms duration is specified, the server should wait that
  long in between sending each response message.
-/
def bidiStream (client : Client) (options : Connect.CallOptions := {}) :
    Connect.RpcM (Connect.BidiStreamCall connectrpc.conformance.v1.BidiStreamRequest connectrpc.conformance.v1.BidiStreamResponse) :=
  client.connection.bidiStream Spec.bidiStream options

/--
A unary endpoint that the server should not implement and should instead
return an unimplemented error when invoked.
-/
def unimplemented (client : Client) (request : connectrpc.conformance.v1.UnimplementedRequest) (options : Connect.CallOptions := {}) :
    Connect.RpcM connectrpc.conformance.v1.UnimplementedResponse :=
  client.connection.unary Spec.unimplemented request options

/--
A unary endpoint denoted as having no side effects (i.e. idempotent).
Implementations should use an HTTP GET when invoking this endpoint and
leverage query parameters to send data.
-/
def idempotentUnary (client : Client) (request : connectrpc.conformance.v1.IdempotentUnaryRequest) (options : Connect.CallOptions := {}) :
    Connect.RpcM connectrpc.conformance.v1.IdempotentUnaryResponse :=
  client.connection.unary Spec.idempotentUnary request options

end Client

end ConformanceService

end connectrpc.conformance.v1
